name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (SQLite)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-sqlite.txt

      - name: Run tests
        env:
          DISABLE_POLLER: "1"
          DATABASE_URL: "sqlite+aiosqlite:///./test.db"
        run: |
          pytest -q
name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (SQLite path)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-sqlite.txt

      - name: Run tests
        env:
          DISABLE_POLLER: "1"
          DATABASE_URL: "sqlite+aiosqlite:///./ci.db"
        run: |
          pytest -q
