name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR (optional)
        uses: docker/login-action@v3
        if: ${{ github.repository_owner != '' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (Docker Hub + GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          provenance: false
          sbom: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/serri-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/serri-backend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/serri-backend:latest
            ghcr.io/${{ github.repository_owner }}/serri-backend:${{ github.sha }}
